version: "3.9"

services:
  pipeline:
    build: .
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./report:/app/report
    command: python src/preprocessing.py

  test:
    build: .
    command: python -m pytest tests/test.py -v

  train:
    build: .
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./report:/app/report
    command: python src/modeling.py
